# For more information about the configurations used
# in this file, please see the Travis CI documentation:
# https://docs.travis-ci.com

before_install:
- openssl aes-256-cbc -K $encrypted_e95fcac9a2dd_key -iv $encrypted_e95fcac9a2dd_iv
  -in travis.enc -out travis -d

after_success:
  - |

      # Automatically update the content from the `dist/` directory

      $(npm bin)/travis-after-all \
        && $(npm bin)/set-up-ssh -k "$encrypted_e95fcac9a2dd_key" \
                                 -iv "$encrypted_e95fcac9a2dd_iv" \
                                 --path-encrypted-key ".travis/travis.enc" \
        && $(npm bin)/commit-changes --branch "master" \
                                     --commands "npm run build" \
                                     --commit-message "Update content from the \`dist\` directory [skip ci]"

env:
  global:
    - secure: "uZ0R71TG9AR+kbfM9rwa8PPNr3f9E0C4OuA0s6g0Gq15bBcpVxPvus0/eJdW+O2NSzZE1GbzS//hBiP+chK/8X4DyNIRutlGk5RYdnTTFEaZo9jp0BvlvprUYlGgpprR/531zQ9ahkc0STwVvzurGzlcF4NNMiISAJJ1IdQZABc="

git:
  depth: 10

language: node_js

node_js:
  - 4
  - 6
  - 7

sudo: false
